apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  labels:
    app.kubernetes.io/name: victoriametrics
spec:
  selector:
    app.kubernetes.io/name: victoriametrics
  ports:
    - name: https
      port: 8428
      targetPort: https
      protocol: TCP
