apiVersion: v1
kind: Service
metadata:
  name: vmalert
  labels:
    app.kubernetes.io/name: vmalert
spec:
  selector:
    app.kubernetes.io/name: vmalert
  ports:
    - name: https
      port: 8880
      targetPort: https
      protocol: TCP
